version: 2.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build:
  verbosity: minimal
deploy:
- provider: FTP
  host: thenoodlemummy.com
  protocol: ftp
  username: Appveyor
  password:
    secure: PYK20u4YC+/u5AT+RheK5w==
  folder: /Mummybot
  artifact: MummybotRewrite\bin\release\net9.0\MummyBot.zip
after_deploy:
- ps: Invoke-RestMethod -Method 'Get' -Uri https://thenoodlemummy.com:22554/api/deployment/deploy
on_success:
- pwsh: Invoke-RestMethod -Method 'Get' -Uri http://thenoodlemummy.com:22554/api/deployment/BuildSuccess
on_failure:
- pwsh: Invoke-RestMethod -Method 'Get' -Uri http://thenoodlemummy.com:22554/api/deployment/Buildfailed
on_finish:
- pwsh: Invoke-RestMethod -Method 'Get' -Uri http://thenoodlemummy.com:22554/api/deployment/BuildFinished
