version: '2.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - cmd: dotnet tool install --global dotnet-ef --version 3.0.0-* #this is required to be able to push migrations (if i can find a way to do this without exposing the connection string)
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./MummybotRewrite/Mummybot.csproj --verbosity m
build_script:
  # output will be in ./src/bin/release/netcoreapp3.0/publish
  - cmd: dotnet publish ./MummybotRewrite/Mummybot.csproj -c release
after_build:
  # For once the build has completed
artifacts:
 - path: 'MummybotRewrite\bin\release\netcoreapp3.0\publish'
   name: MummyBot
   type: WebDeployPackage
clone_depth: 1
test_script:
   

deploy: 
- provider: Environment
  name: DeployMummyBot
  
on_success:
  - ps: Invoke-RestMethod -Method 'Get' -Uri http://thenoodlemummy.tk:22555/api/deployment/BuildSuccess

# on build failure
on_failure:
  - ps: Invoke-RestMethod -Method 'Get' -Uri http://thenoodlemummy.tk:22555/api/deployment/Buildfailed
    
after_deploy:
  - ps: start-sleep -s 60 #delay 60sec as appveyor doesnt relize its still transfering the files and already report deployment sucessfull
  - ps: Invoke-RestMethod -Method 'Get' -Uri http://thenoodlemummy.tk:22555/api/deployment/deploy
