// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mummybot.Database;

namespace Mummybot.Migrations
{
    [DbContext(typeof(TokenStore))]
    [Migration("20190626203214_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mummybot.Database.Entities.Token", b =>
                {
                    b.Property<string>("BotName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BotToken");

                    b.HasKey("BotName");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
